# Name of this workflow

name: CI

# Controls when the workflow will run – only on cron or manual workflow dispatch
on:
    # Cron: Once at 9am UTC (4am EST)
    schedule:
        - cron: '0 9 * * *'

    workflow_dispatch:

# This workflow consists of 1 job: `build`
jobs:
    build:
        # The test runner the job will run on
        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            # Install – always use `npm ci` so that package-lock.json is used
            - name: Run Cypress
              run: |
                  npm ci
                  npx cypress run

            # This is the step that will transfer files to the s3 bucket
            - name: Publish new dictionary file to nytimes s3 bucket
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --follow-symlinks
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  SOURCE_DIR: 'cypress/fixtures'
