# This workflow fires when the payload
name: Repository Dispatch workflow
on:
    workflow_dispatch:

# Jobs can run sequentially or in parallel
jobs:
    print-stuff:
        name: Print Stuff
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Payload
              run: |
                  echo ${{ github.event.client_payload }}
